Parameters:
  ImageId:
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Default: /aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2
  EnvType:
    Description: Environment Name
    Default: test
    Type: String
    AllowedValues:
      - prod
      - test
    ConstraintDescription: must be prod or test
Conditions:
  CreateProdResources: !Equals [ !Ref EnvType, prod]
Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref ImageId
      InstanceType: t2.micro

  NewVolume:
    Type: AWS::EC2::Volume
    Condition: CreateProdResources
    Properties:
      AvailabilityZone:
        !GetAtt  EC2Instance.AvailabilityZone
      Size: 1

  MountPoint:
    Type: AWS::EC2::VolumeAttachment
    Condition: CreateProdResources
    Properties:
      Device: /dev/sdh
      InstanceId: !Ref EC2Instance
      VolumeId: !Ref NewVolume

Outputs:
  VolumeId:
    Condition: CreateProdResources
    Value:
      !Ref NewVolume
